export const templates = [
  "{character}, but in the style of {cartoon|anime|video_game}",
  "{character} but as {a} {video_game} boss",
  "{person} being stalked by {character}, but they're cool with it",
  "{character} appearing on an episode of {tv_show|cartoon|anime}",
  "{property} but now there's {character} and the plot stopped making sense",
  "{character} having no fun at all while participating in {activity}",
  "{character} gobbling down a whole buncha {foods}",
  "{person} eating {foods} with {person}, but one of them isn't having a good time",
  "{character} winning {a} {food} eating contest",
  // "{person}'s lesser known twin, "
  "{character} getting {attacked} by {character}",
  "{character} playing with {a} {2:adjective} {toy}",
  "{character} {attacking} Hitler in his stupid, facist face",
  "the latest {video_game|video_game_company} game being presented at E3 by {character}",
  "{character} attacking {character} with dual uzis",
  "{character} starting their own {place}, but with Blackjack! And Hookers!",
  "{character} dropping the sickest beats",
  "{character} {exaggeration} slaying at guitar",
  "{character} {attacking} NPCs in {video_game}",
  "{character} drawing {adjective} anime",
  "{character} drawing characters from {anime|video_game|cartoon} poorly",
  "{character} doing the jitterbug",
  "{character} decorating a bedroom for {character}",
  "{character} smoking potpourri",
  "{character} traveling back in time",
  "{character} jumping the non-preverbial shark... just like Fonzy!",
  "{character} lighting fires",
  "{character} binge-watching {tv_show|cartoon|anime} on Netflix",
  "{character} conducting evil experiments in the name of SCIENCE",
  "{character} contemplating their very existence",
  "{character} questioning whether any of this is real... like, actually real",
  "{character} karate chopping people in the throat",
  "{character} running in reverse",
  "{character} shouting insults at strangers",
  "{character} burninating the peasants",
  "{character} burninating all the people",
  "{character} handling a barrage of insults like a pro",
  "{character} answering life's most important questions",
  "{character} performing unspeakable acts",
  "{character} eating hands",
  "{character} killing zombies",
  "{character} punching Hitler right in his stupid, facist face",
  "{character} colluding with Russia",
  "{character} piloting a giant, cybernetic suit",
  "{character} hacking all of the government's secrets",
  "{character} thinking about their childhood sled while on their death bed",
  "{character} {1:exaggeration} killing a guy named \"Bill\"",
  "{character} leading the police on an extremely slow car chase",
  "{character} laughing at someone's inability to draw {anime|cartoon|video_game} from memory",
  "{character} striking an unflattering pose",
  "{character} in {a} {1:adjective} {dance} class and people won't stop looking",
  "{character} but as a cybernetic warrior, with nunjucks... and lazer beams!",
  "{character} speaking in wingdings",
  "{character} being forced to watch the Emoji Movie over and over and over",
  "{character} singing, \"BELIEVE IT OR NOT, I'M WALKING ON AIR, I NEVER THOUGHT I WOULD FEEL SO FREE-EE-EEEEEE\" as loud as they can",
  "{character} going through TSA security",
  "{character} waiting in line at the DMV",
  "{character} but as a {1:adjective} comic book character",
  "{character} as a 1920s cartoon character",
  "{character} doing the {dance}",
  "{character} performing magic tricks... for adults",
  "{character} drawing innapropriate pictures as a form of vandalism",
  "{character} playing a VR game while throwing up absolutely everywhere",
  "{character} cheating at {activity}",
  "{character} absolutely failing at being cool",
  "{character} flexing their muscles and showin off their sweet, sweet bod",
  "{character} going on vacation but it's awful",
  "{character} acting out some terrible {property} fan-fiction that they wrote",
  "{character} ruining absolutely everything for everyone",
  "{character} listening to MACINTOSH PLUS - リサフランク420 / 現代のコンピュー",
  "{character} getting a skeezy feel up",
  "{character} playing \"Wonderwall\" on their guitar like an absolute douche",
  "{character} wishing you a Merry Christmas, but there's a \"war on Christmas\"",
  "{character} pushing it to the limit... and something broke",
  "{character} drop kicking a Papa Murphy's pizza while listening to the \"Dropkick Murphys\"",
  "{character} browsing 4chan and coming to understand what depravity actually is",
  "{character} performing {a} {1:adjective} musical rendition of {movie|tv_show}",
  "{character} vaping while wearing a fedora (a winning combination)",
  "{character} facing themselves in the mirror... like... their REAL self",
  "{character} revealing their final form",
  "{character} failing to read the room in a tense and awkward situation",
  "{character} preparing a dish for Gordon Ramsey but IT'S F*&%ING RAW",
];

export const places = [
  "party",
  "casino",
  "bingo hall",
  "museum",
  "aquarium",
  "department of motor vehicles",
  "grocery store",
  "warehouse",
  "clothing store",
  "mall",
  "{food} restaurant",
  "toy store",
  "White House",
  "showroom",
];

export const activities = [
  "sports",
  "football",
  "soccer",
  "baseball",
  "foosball",
  "tennis",
  "ping pong",
  "golf",
  "board games",
  "Dungeons & Dragons",
  "chess",
  "video games",
];

export const dances = [
  "macarena",
  "jitterbug",
  "cha cha slide",
  "electric shuffle",
  "charleston",
  "tango",
];

export const animals = [
  "otter",
  "weasel",
  "lion",
  "cougar",
  "bear",
  "t-rex",
  "stoat",
  "ferret",
  "badger",
  "doggo",
  "puppo",
  "gopher",
  "penguin",
  "sloth",
  "spider",
  "scorpion",
  "ant",
  "flea",
  "parrot",
];

export const foods = [
  "pizza",
  "hot dog",
  "sausage",
  "pancake",
  "hamburger",
  "sushi roll",
  "falafel",
  "bagel",
];

export const creatures = [
  "anthropomorphic peanut",
  "brave little toaster",
  "zombie",
  "vampire",
  "werewolf",
  "robot",
  "android",
  "cyborg",
  "demogorgon",
  "bird-person",
  "hobbit",
  "monster",
  "elf",
  "ghoul",
  "ghost",
  "orc",
  "goblin",
  "monster",
  "dragon",
  "gelfling",
  "skeksi",
];

export const toys = [
  "Furby",
  "Teddy Ruxpin",
  "Transformer",
  "Lego Figurine",
  "Polly Pocket",
  "Barbie doll",
  "Ken doll",
  "GI Joe",
];

export const bodyParts = [
  "throat",
  "face",
  "hands",
  "legs",
  "knee caps",
  "elbows",
  "baby maker",
  "chest",
  "boobal region",
];

export const badPeople = [
  "Adolf Hitler",
  "Donald Trump",
];

export const attacks = [
  "punch",
  "kick",
  "roundhouse kick",
  "falcon punch",
  "one punch",
  "pummel",
  "dropkick",
  "attack",
  "assault",
];

export const exaggerations = [
  "racically",
  "overwhelmingly",
  "abundantly",
  "aggressively",
  "absolutely",
  "obnoxiously",
  "epicly",
  "extremely",
  "overly",
];

export const insults = [
  "fat",
  "stupid",
  "dumb",
  "idiotic",
  "racist",
  "cocky",
  "ignorant",
  "cruel",
  "douchey",
  "jerky",
  "irritating",
  "frustrating",
];

export const adjectives = [
  "anxious",
  "jealous",
  "crafty",
  "amused",
  "bored",
  "dying",
  "wealthy",
  "magical",
  "radical",
  "cunning",
  "mean",
  "cruel",
  "angry",
  "jovial",
  "happy",
  "harsh",
  "agitated",
  "woeful",
  "depressed",
  "cranky",
  "miserable",
  "disgruntled",
  "grand",
  "wonderful",
  "whimsical",
  "majestic",
  "royal",
  "mutated",
  "disfigured",
  "crippled",
  "broken",
  "homeless",
  "sick",
  "dying",
  "demented",
  "awkward",
  "busty",
  "chubby",
  "innapropriately dressed",
  "radical",
  "extreme",
  "tubular",
  "lazy",
  "snazzy",
  "lonely",
  "obnoxious",
  "adorable",
  "wild",
  "psychic",
  "telepathic",
  "all-powerful",
  "smooth-talking",
  "fast-talking",
  "horrific",
  "huge",
  "tiny",
  "gelatinous",
  "gooey",
  "slimy",
  "singing",
  "rapping",
];

export const colors = [
  "black",
  "white",
  "rainbow",
  "green",
  "blue",
  "red",
  "pink",
  "purple",
  "magenta",
  "cyan",
  "yellow",
  "orange",
  "brown",
  "beige",
  "tan",
  "neon",
  "pastel",
];

export const occupations = [
  "person",
  "scientist",
  "rock star",
  "professor",
  "baby",
  "politician",
  "president",
  "United States President",
  "chef",
  "king",
  "queen",
  "criminal",
  "thief",
  "student",
  "martial artist",
  "historical figure",
  "pirate",
  "knight",
  "caveman",
  "ninja",
  "samurai",
  "wizard",
  "boomer",
  "head school master",
  "teacher",
  "programmer",
  "designer",
  "artist",
  "musician",
  "senator",
  "Democrat",
  "Republican",
  "handyman",
  "electrician",
];

export const groupNames = [
  "pack",
  "herd",
  "flock",
  "school",
];

export const anime = [
  "Dragonball Z",
  "Attack on Titan",
  "One Punch Man",
  "One Piece",
  "Naruto",
  "My Hero Academia",
  "Poke'mon",
  "Digimon",
  "Rurouni Kenshin",
  "Yu Yu Hakusho",
  "Hunter x Hunter",
  "Inuyasha",
  "Ghost in the Shell",
];

export const cartoons = [
  "Lloyd in Space",
  "Dexter's Lab",
  "Powerpuff Girls",
  "Cow & Chicken",
  "Ren & Stimpy",
  "Johnny Bravo",
  "Courage the Cowardly Dog",
  "Aqua Teen Hunger Force",
  "Sealab 2021",
  "Rick & Morty",
  "Flintstones",
  "Family Guy",
  "Simpsons",
  "Rugrats",
  "Spongebob Squarepants",
  "Star Wars: The Clone Wars",
  "Courage the Cowardly Dog",
  "Samurai Jack",
];

export const movies = [
  "Star Wars",
  "Matrix",
  "Pee Wee's Big Adventure",
  "Beetlejuice",
  "Harry Potter",
  "Star Wars Episode 1: The Phantom Menace",
  "Spider-Man",
  "The Nightmare Before Christmas",
];

export const tvShows = [
  "Friends",
  "How I Met Your Mother",
  "Stranger Things",
  "Robot Chicken",
  "IT Crowd",
  "The Office",
  "X-Files",
  "{person}'s new cooking show",
  "Power Rangers",
];

export const videoGames = [
  "Sonic the Hedgehog",
  "Super Mario",
  "Legend of Zelda",
  "Dark Souls",
  "Banjo-Kazooie",
  "Call of Duty",
  "Titanfall",
  "Halo",
  "Overwatch",
  "World of Warcraft",
  "Fallout",
  "Apex Legends",
  "Rainbow Six",
  "Counter Strike",
  "Team Fortress",
  "Poke'mon",
  "Minecraft",
  "Fortnite",
  "Unreal Tournament",
  "Gears of War",
  "Starcraft",
  "Hitman",
  "Star Fox",
  "Metroid",
  "Silent Hill",
  "Resident Evil",
  "Assassin's Creed",
  "Dying Light",
];

export const videoGameCompanies = [
  "Nintendo",
  "Sony",
  "X-Box",
  "Naughty Dog",
  "Hideo Kojima",
  "Sega",
  "Electronic Arts",
  "Double Fine",
  "Ubisoft",
  "Bethesda",
];

export const people = [
  "Nathan Yaffe",
  "Caldwell Tanner",
  "Jacob Andrews",
  "Julita Lepetit",
  "Karain Farek",
  "Keanu Reeves",
  "Julia Andrews",
  "Dwayne \"The Rock\" Johnson",
  "Hulk Hogan",
  "Johnny Depp",
  "Bill Gates",
  "Steve Jobs",
  "Arnold Schwarzenegger",
  "Jim Carrey",
  "Emma Watson",
  "Daniel Radcliffe",
  "Leonardo DiCaprio",
  "Tom Cruise",
  "Brad Pitt",
  "Morgan Freeman",
  "Matt Damon",
  "Tom Hanks",
  "Sylvester Stallone",
  "Will Smith",
  "Cameron Diaz",
  "Clint Eastwood",
  "George Clooney",
  "Steven Spielberg",
  "Harrison Ford",
  "Mark Hammil",
  "Robert De Niro",
  "Al Pacino",
  "Robert Downey Jr.",
  "Russell Crowe",
  "Liam Neeson",
  "Kate Winslet",
  "Mark Wahlberg",
  "Natalie Portman",
  "Pierce Brosnan",
  "Sean Connery",
  "Orlando Bloom",
  "Jackie Chan",
  "Angelina Jolie",
  "Adam Sandler",
  "Scarlett Johansson",
  "Heath Ledger",
  "Anne Hathaway",
  "Jessica Alba",
  "Kiera Knightly",
  "Bradley Cooper",
  "Will Ferrel",
  "Nicolas Cage",
  "Daniel Craig",
  "Ian McKellen",
  "Bruce Willis",
  "Samuel L Jackson",
  "Ben Stiller",
  "Tommy Lee Jones",
  "Steve Carell",
  "Shia LaBeouf",
  "Megan Fox",
  "James Franco",
  "Mel Gibson",
  "Vin Diesel",
];