export default [
  "An angry",
  "A slightly agitated",
  "A woeful",
  "A depressed",
  "An amused",
  "A cranky",
  "A jovial",
  "An overlay happy",
  "A miserable",
  "A disgruntled",
  "A grand",
  "A wonderful",
  "A whimsical",
  "The majestic",
  "The worst",
  "The best",
  "A royal",
  "A mutated",
  "A disfigured",
  "A crippled",
  "A broken",
  "A wealthy",
  "A homeless",
  "A sick",
  "A dying",
  "A demented",
  "A big, red",
  "An awkward",
  "A busty",
  "A chubby",
  "An innapropriately dressed",
  "A radical",
  "An extreme",
  "A tubular",
  "A lazy",
  "A snazzy",
  "A lonely",
  "An obnoxious",
  "An adorable",
  "A wild",
  "A psychic",
  "A telepathic",
  "An all-powerful",
  "A smooth-talking",
  "A fast-talking",
  "A horrific",
  "A huge",
  "A tiny",
  "A gelatinous",
  "A gooey",
  "A slimy",
  "A singing",
  "A rapping",
];