export default [
  "with a keytar",
  "with dual uzis",
  "playing X-Box",
  "dropping sick beats",
  "in disguise",
  "slaying the guitar",
  "in minecraft",
  "drawing anime",
  "recording drawfee",
  "doing the jitterbug",
  "decorating a bedroom",
  "smoking potpourri",
  "traveling back in time",
  "jumping the shark",
  "lighting fires",
  "binging on Netflix",
  "conducting evil experiments",
  "contemplating their very existence",
  "questioning whether any of this is real... like, actually real",
  "as a Dark Souls boss",
  "karate chopping people in the throat",
  "running in reverse",
  "doing SCIENCE",
  "shouting insults at strangers",
  "burninating the peasants",
  "burninating all the people",
  "handling a barrage of insults like a pro",
  "being boring",
  "answering lifes most important question",
  "performing unspeakable acts",
  "eatings hands",
  "killing zombies",
  "punching Hitler right in his stupid, racist face",
  "colluding with Russia",
  "crunching the numbers",
  "piloting a giant, cybernetic suit",
  "hacking the government",
  "thinking about their childhood sled while on their death bed",
  "killing a guy named Bill",
  "leading the police on an extremely slow vehicular chase",
  "laughing at someone's inability to draw Poke'mon from memory",
  "striking an unflattering pose",
  "as steampunk character",
  "as a cyborg warrior",
];