export default [
  "with a keytar",
  "with dual uzis",
  "playing X-Box",
  "dropping sick beats",
  "in disguise",
  "slaying the guitar",
  "in minecraft",
  "drawing anime",
  "recording drawfee",
  "doing the jitterbug",
  "decorating... just, decorating",
  "smoking potpourri",
  "time traveling",
  "jumping the shark",
  "lighting fires",
  "binging on Netflix",
  "conducting evil experiments",
  "contemplating their very existence",
  "questioning whether any of this is real... like, actually real",
  "as a Dark Souls boss",
  "karate chopping people in the throat",
  "running in reverse",
  "doing SCIENCE",
];