export default [
  "with a keytar",
  "with dual uzis",
  "playing X-Box",
  "dropping the sickest of beats",
  "in disguise",
  "slaying at guitar",
  "in Minecraft",
  "drawing anime",
  "doing the jitterbug",
  "decorating a bedroom",
  "smoking potpourri",
  "traveling back in time",
  "jumping the shark",
  "lighting fires",
  "binging on Netflix",
  "conducting evil experiments",
  "contemplating their very existence",
  "questioning whether any of this is real... like, actually real",
  "as a Dark Souls boss",
  "karate chopping people in the throat",
  "running in reverse",
  "doing SCIENCE",
  "shouting insults at strangers",
  "burninating the peasants",
  "burninating all the people",
  "handling a barrage of insults like a pro",
  "answering life's most important questions",
  "performing unspeakable acts",
  "eating hands",
  "killing zombies",
  "punching Hitler right in his stupid, facist face",
  "colluding with Russia",
  "crunching the numbers",
  "piloting a giant, cybernetic suit",
  "hacking the all of the government's secrets",
  "thinking about their childhood sled while on their death bed",
  "killing a guy named Bill",
  "leading the police on an extremely slow vehicular chase",
  "laughing at someone's inability to draw Poke'mon from memory",
  "striking an unflattering pose",
  "as steampunk character",
  "as a cybernetic warrior",
  "speaking in wingdings",
  "being forced to watch the Emoji Movie over and over and over",
  "singing, \"BELIEVE IT OR NOT, I'M WALKING ON AIR, I NEVER THOUGHT I WOULD FEEL SO FREE-EE-EEEEEE\" as loud as they can",
  "going through TSA security",
  "waiting in line at the DMV",
  "but as a Todd McFarlane comic book character",
  "as a 1920s cartoon character",
  "doing the Macarena",
  "performing magic tricks for adults",
  "livin' la vida loca",
  "drawing innapropriate pictures as a form of vandalism",
  "playing a VR game while throwing up everywhere",
  "cheating at soccer",
  "absolutely failing at being cool",
  "that won't stop talking",
  "flexing their muscles and showin off their sweet, sweet bod",
  "going on vacation but it's awful",
];